spring:
  application:
    name: responsibles
  datasource:
    url: jdbc:postgresql://localhost:3333/registerUsers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mt8822774@gmail.com
    password: anyr wqjz syup bpnp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


